package mungbean;

import jdave.Specification;
import jdave.contract.EqualsHashCodeContract;
import jdave.junit4.JDaveRunner;

import org.junit.runner.RunWith;

@RunWith(JDaveRunner.class)
public class ObjectIdSpec extends Specification<ObjectId> {
	public class WithGivenBytes {
		public ObjectId create() {
			return new ObjectId(new byte[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 });
		}

		public void toStringReturnsHumanReadableString() {
			specify(context.toString(), does.equal("ObjectId[010203:040506:070809:0a0b0c]"));
		}

		public void meetsEqualsAndHashCodeContracts() {
			specify(context, new EqualsHashCodeContract<ObjectId>() {

				@Override
				protected ObjectId equal() {
					return new ObjectId(new byte[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 });
				}

				@Override
				protected ObjectId nonEqual() {
					return new ObjectId(new byte[] { 2, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 });
				}

				@Override
				protected ObjectId subType() {
					return new ObjectId(new byte[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 }) {

					};
				}
			});
		}
	}

	public class WithAutoGenerated {
		public ObjectId create() {
			return new ObjectId();
		}

		public void isNotEqualToOtherOne() {
			specify(context.equals(new ObjectId()), does.equal(false));
		}
	}
}
