/*
   Copyright 2009 Janne Hietamäki

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */
package mungbean;

import jdave.Specification;
import jdave.contract.EqualsHashCodeContract;
import jdave.junit4.JDaveRunner;

import org.junit.runner.RunWith;

@RunWith(JDaveRunner.class)
public class ObjectIdSpec extends Specification<ObjectId> {
	public class WithGivenBytes {
		public ObjectId create() {
			return new ObjectId(new byte[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 });
		}

		public void toStringReturnsHumanReadableString() {
			specify(context.toString(), does.equal("ObjectId(0102030405060708090a0b0c)"));
		}

		public void meetsEqualsAndHashCodeContracts() {
			specify(context, new EqualsHashCodeContract<ObjectId>() {

				@Override
				protected ObjectId equal() {
					return new ObjectId(new byte[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 });
				}

				@Override
				protected ObjectId nonEqual() {
					return new ObjectId(new byte[] { 2, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 });
				}

				@Override
				protected ObjectId subType() {
					return new ObjectId(new byte[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 }) {

					};
				}
			});
		}
	}

	public class WithAutoGenerated {
		public ObjectId create() {
			return new ObjectId();
		}

		public void isNotEqualToOtherOne() {
			specify(context.equals(new ObjectId()), does.equal(false));
		}
	}
}
